#!/bin/bash

export LOG_FILE="./logile.log"
export LOG_LEVEL="2"

# Check the first argument to the script
if [ "$1" == "install" ]; then
    #echo "Running installation..."
    #echo "Installing ts-node"
    npm install ts-node --save
    #echo "Ts-node installed."
    #echo "Installing yargs"
    npm install yargs --save
    #echo "Yargs installed."
    #echo "Installing axios"
    npm install axios --save
    #echo "Axios installed."
    #echo "Installing child_process"
    npm install child_process --save
    #echo "Child_process installed."
    #echo "Installing path"
    npm install path --save
    #echo "Path installed."
    #echo "Installing winston"
    npm install winston --save
    #echo "Winston installed."
    #echo "Ready to run other commands."
    exit 0
elif [[ "$1" == "URL_FILE" ]]; then
    url="$2"
    rm -rf "cli_storage"/*
    #echo "Running URL_FILE command with url: $url"
    #echo "Clearing local package storage..."
    #echo "Compiling essential scripts..."
    tsc metrics.ts
    tsc logger.ts
    tsc npm-github-netscore.ts
    #echo "Scripts compiled."
    npx ts-node run.ts "URL_FILE" "$url"
    if [ $? -ne 0 ]; then
    echo "An error occurred. Enable or check logfile for debugging"
    exit 1
    else
    exit 0
    fi
elif [ "$1" == "test" ]; then
    npx ts-node run.ts $@
    if [ $? -ne 0 ]; then
      echo "An error occurred. Must install dependencies!"
      exit 1
    else
    exit 0
    fi
else
    echo "Unknown command: $1"
    echo "Please us one of these commands: install', 'URL_FILE', or 'test'"
    exit 1
fi

