#!/bin/bash

# Check the first argument to the script
if [ "$1" == "install" ]; then
    echo "Running installation..."
    echo "Installing ts-node"
    npm install ts-node --save
    echo "Ts-node installed.";
    echo "Installing yargs"
    npm install yargs --save
    echo "Yargs installed.";
    echo "Installing axios"
    npm install axios --save
    echo "Axios installed.";
    echo "Installing child_process"
    npm install child_process --save
    echo "Child_process installed.";
    echo "Ready to run other commands.";
elif [ "$1" == "URL_FILE" ]; then
    npx ts-node run.ts $@
    if [ $? -ne 0 ]; then
      echo "An error occurred. Must install dependencies!"
    fi
elif [ "$1" == "test" ]; then
    npx ts-node run.ts $@
    if [ $? -ne 0 ]; then
      echo "An error occurred. Must install dependencies!"
    fi
else
    echo "Unknown command: $1"
    echo "Please us one of these commands: install', 'URL_FILE', or 'test'";
    exit 1
fi

