/*
 * ECE 461 - Fall 2023 - Project Phase 2
 * API for ECE 461/Fall 2023/Project Phase 2: A Trustworthy Module Registry\"  All endpoints have BASELINE or NON-BASELINE listed. Please read through all descriptions before raising questions.   A package ID is unique identifier for Package and Version. (Key idea -> id is unique for all pacakges).  Eg.       PacakgeName: Alpha, PackageVersion: 1.1.1 -> PackageID: 988645763         PacakgeName: Alpha, PackageVersion: 1.3.2 -> PackageID: 357898765
 *
 * OpenAPI spec version: 2.4.1
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PackageRegEx model module.
 * @module model/PackageRegEx
 * @version 2.4.1
 */
export class PackageRegEx {
  /**
   * Constructs a new <code>PackageRegEx</code>.
   * @alias module:model/PackageRegEx
   * @class
   * @param regEx {String} A regular expression over package names and READMEs that is used for searching for a package
   */
  constructor(regEx) {
    this.regEx = regEx;
  }

  /**
   * Constructs a <code>PackageRegEx</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PackageRegEx} obj Optional instance to populate.
   * @return {module:model/PackageRegEx} The populated <code>PackageRegEx</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PackageRegEx();
      if (data.hasOwnProperty('RegEx'))
        obj.regEx = ApiClient.convertToType(data['RegEx'], 'String');
    }
    return obj;
  }
}

/**
 * A regular expression over package names and READMEs that is used for searching for a package
 * @member {String} regEx
 */
PackageRegEx.prototype.regEx = undefined;

