/*
 * ECE 461 - Fall 2023 - Project Phase 2
 * API for ECE 461/Fall 2023/Project Phase 2: A Trustworthy Module Registry\"  All endpoints have BASELINE or NON-BASELINE listed. Please read through all descriptions before raising questions.   A package ID is unique identifier for Package and Version. (Key idea -> id is unique for all pacakges).  Eg.       PacakgeName: Alpha, PackageVersion: 1.1.1 -> PackageID: 988645763         PacakgeName: Alpha, PackageVersion: 1.3.2 -> PackageID: 357898765
 *
 * OpenAPI spec version: 2.4.1
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SemverRange model module.
 * @module model/SemverRange
 * @version 2.4.1
 */
export class SemverRange {
  /**
   * Constructs a new <code>SemverRange</code>.
   * @alias module:model/SemverRange
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SemverRange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SemverRange} obj Optional instance to populate.
   * @return {module:model/SemverRange} The populated <code>SemverRange</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SemverRange();
    }
    return obj;
  }
}
