/*
 * ECE 461 - Fall 2023 - Project Phase 2
 * API for ECE 461/Fall 2023/Project Phase 2: A Trustworthy Module Registry\"  All endpoints have BASELINE or NON-BASELINE listed. Please read through all descriptions before raising questions.   A package ID is unique identifier for Package and Version. (Key idea -> id is unique for all pacakges).  Eg.       PacakgeName: Alpha, PackageVersion: 1.1.1 -> PackageID: 988645763         PacakgeName: Alpha, PackageVersion: 1.3.2 -> PackageID: 357898765
 *
 * OpenAPI spec version: 2.4.1
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Ece461Fall2023ProjectPhase2);
  }
}(this, function(expect, Ece461Fall2023ProjectPhase2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PackageRating', function() {
      beforeEach(function() {
        instance = new Ece461Fall2023ProjectPhase2.PackageRating();
      });

      it('should create an instance of PackageRating', function() {
        // TODO: update the code to test PackageRating
        expect(instance).to.be.a(Ece461Fall2023ProjectPhase2.PackageRating);
      });

      it('should have the property busFactor (base name: "BusFactor")', function() {
        // TODO: update the code to test the property busFactor
        expect(instance).to.have.property('busFactor');
        // expect(instance.busFactor).to.be(expectedValueLiteral);
      });

      it('should have the property correctness (base name: "Correctness")', function() {
        // TODO: update the code to test the property correctness
        expect(instance).to.have.property('correctness');
        // expect(instance.correctness).to.be(expectedValueLiteral);
      });

      it('should have the property rampUp (base name: "RampUp")', function() {
        // TODO: update the code to test the property rampUp
        expect(instance).to.have.property('rampUp');
        // expect(instance.rampUp).to.be(expectedValueLiteral);
      });

      it('should have the property responsiveMaintainer (base name: "ResponsiveMaintainer")', function() {
        // TODO: update the code to test the property responsiveMaintainer
        expect(instance).to.have.property('responsiveMaintainer');
        // expect(instance.responsiveMaintainer).to.be(expectedValueLiteral);
      });

      it('should have the property licenseScore (base name: "LicenseScore")', function() {
        // TODO: update the code to test the property licenseScore
        expect(instance).to.have.property('licenseScore');
        // expect(instance.licenseScore).to.be(expectedValueLiteral);
      });

      it('should have the property goodPinningPractice (base name: "GoodPinningPractice")', function() {
        // TODO: update the code to test the property goodPinningPractice
        expect(instance).to.have.property('goodPinningPractice');
        // expect(instance.goodPinningPractice).to.be(expectedValueLiteral);
      });

      it('should have the property pullRequest (base name: "PullRequest")', function() {
        // TODO: update the code to test the property pullRequest
        expect(instance).to.have.property('pullRequest');
        // expect(instance.pullRequest).to.be(expectedValueLiteral);
      });

      it('should have the property netScore (base name: "NetScore")', function() {
        // TODO: update the code to test the property netScore
        expect(instance).to.have.property('netScore');
        // expect(instance.netScore).to.be(expectedValueLiteral);
      });

    });
  });

}));
