/*
 * ECE 461 - Fall 2023 - Project Phase 2
 * API for ECE 461/Fall 2023/Project Phase 2: A Trustworthy Module Registry\"  All endpoints have BASELINE or NON-BASELINE listed. Please read through all descriptions before raising questions.   A package ID is unique identifier for Package and Version. (Key idea -> id is unique for all pacakges).  Eg.       PacakgeName: Alpha, PackageVersion: 1.1.1 -> PackageID: 988645763         PacakgeName: Alpha, PackageVersion: 1.3.2 -> PackageID: 357898765
 *
 * OpenAPI spec version: 2.4.1
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Ece461Fall2023ProjectPhase2);
  }
}(this, function(expect, Ece461Fall2023ProjectPhase2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Ece461Fall2023ProjectPhase2.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('createAuthToken', function() {
        it('should call createAuthToken successfully', function(done) {
          // TODO: uncomment, update parameter values for createAuthToken call and complete the assertions
          /*

          instance.createAuthToken(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Ece461Fall2023ProjectPhase2.AuthenticationToken);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('packageByNameDelete', function() {
        it('should call packageByNameDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for packageByNameDelete call
          /*

          instance.packageByNameDelete(xAuthorization, name, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('packageByNameGet', function() {
        it('should call packageByNameGet successfully', function(done) {
          // TODO: uncomment, update parameter values for packageByNameGet call and complete the assertions
          /*

          instance.packageByNameGet(name, xAuthorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Ece461Fall2023ProjectPhase2.PackageHistoryEntry);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('packageByRegExGet', function() {
        it('should call packageByRegExGet successfully', function(done) {
          // TODO: uncomment, update parameter values for packageByRegExGet call and complete the assertions
          /*

          instance.packageByRegExGet(body, xAuthorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Ece461Fall2023ProjectPhase2.PackageMetadata);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('packageCreate', function() {
        it('should call packageCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for packageCreate call and complete the assertions
          /*

          instance.packageCreate(body, xAuthorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Ece461Fall2023ProjectPhase2.ModelPackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('packageDelete', function() {
        it('should call packageDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for packageDelete call
          /*

          instance.packageDelete(xAuthorization, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('packageRate', function() {
        it('should call packageRate successfully', function(done) {
          // TODO: uncomment, update parameter values for packageRate call and complete the assertions
          /*

          instance.packageRate(id, xAuthorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Ece461Fall2023ProjectPhase2.PackageRating);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('packageRetrieve', function() {
        it('should call packageRetrieve successfully', function(done) {
          // TODO: uncomment, update parameter values for packageRetrieve call and complete the assertions
          /*

          instance.packageRetrieve(xAuthorization, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Ece461Fall2023ProjectPhase2.ModelPackage);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('packageUpdate', function() {
        it('should call packageUpdate successfully', function(done) {
          // TODO: uncomment, update parameter values for packageUpdate call
          /*

          instance.packageUpdate(body, xAuthorization, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('packagesList', function() {
        it('should call packagesList successfully', function(done) {
          // TODO: uncomment, update parameter values for packagesList call and complete the assertions
          /*
          var opts = {};

          instance.packagesList(body, xAuthorization, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Ece461Fall2023ProjectPhase2.PackageMetadata);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('registryReset', function() {
        it('should call registryReset successfully', function(done) {
          // TODO: uncomment, update parameter values for registryReset call
          /*

          instance.registryReset(xAuthorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
